### ISSUE TITLE
Problems pushing Travis package to chocolatey.org

### ISSUE THREAD

**Issue by gep13** [naveen521kk/au-packages#2]
I have noticed that there have been several attempts to push a new package version for the travis package.  Each of these haven't been successful for the following reason:

```
- Property: 'FlattenedAuthors', Error: 'The field FlattenedAuthors must be a string or array type with a maximum length of '1500'.'
```

This information isn't readily available in the chocolatey client (choco.exe), but there is an open issue on making this better which you can subscribe to here:

https://github.com/chocolatey/chocolatey.org/issues/884

For now, if you reduce the size of the authors element in the travis.nuspec and re-pack the package, you should be able to successfully push it.

**Comment by naveen521kk** [comment]
Thank you very much. Package has been successfully pushed.
